Pending --> Develop a tool to analyze the logs (current logs are added to the repo)
ExtensiveLifeOy/helisimu pull request #12
Opened 2018-04-19 01:36 UTC by ldiago

2018-04-19 07:10 UTC, remware approved these changes

2018-04-19 07:13 UTC, remware requested changes
Remove names

2018-04-19 18:04 UTC, ldiago commented
and now what?

2018-04-26 18:39 UTC, remware approved these changes

2018-04-26 18:39 UTC, merged